name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    env:
      FLUTTER_VERSION: '3.35.7'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Restore shared build caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.gradle
            ~/.cache/flutter
            ~/Library/Caches/CocoaPods
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('pubspec.lock', 'ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-
            ${{ runner.os }}-flutter-

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Fetch platform assets
        run: bash tool/fetch_platform_assets.sh

      - name: Generate Podfile
        run: |
          mkdir -p ios
          FLUTTER_SDK_PATH=$(dirname $(dirname $(which flutter)))

          cat > ios/Podfile << EOF
          platform :ios, '13.0'

          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          # Жестко задаем flutter_root. Больше не читаем Generated.xcconfig.
          def flutter_root
            return "${FLUTTER_SDK_PATH}"
          end

          require File.expand_path(
            File.join('packages', 'flutter_tools', 'bin', 'podhelper'),
            flutter_root
          )

          flutter_ios_podfile_setup

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
            end
          end
          EOF

      - name: Build unsigned IPA
        run: bash tool/ci-ios-build.sh

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: build/ios/ipa/*.ipa
          if-no-files-found: error
          retention-days: 7
